#!/usr/bin/env bash
# This script creates an RSA key pair with the private key named school (protected by passphrase betty).

ssh-keygen -t rsa -b 4096 -C "vagrant@ubuntu" -f ~/.ssh/school -N "betty"
